apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-service
  template:
    metadata:
      labels:
        app: blob-service
    spec:
      #nodeSelector:
      #deployment-group: agent
      containers:
      - name: blob-service
        #image: docker.io/library/blob-service:latest
        image: ubuntu:latest
        command: ["sleep"]
        args: ["infinity"]
          #imagePullPolicy: Never
        ports:
        - containerPort: 3003
        volumeMounts:
        - mountPath: "/mnt/blob-storage"  
          name: nfs-volume
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc  
