apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-service
  template:
    metadata:
      labels:
        app: token-service
    spec:
      nodeSelector:
        deployment-group: master
      containers:
      - name: token-service
        image: docker.io/library/token-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002