apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-service
  template:
    metadata:
      labels:
        app: blob-service
    spec:
      nodeSelector:
        deployment-group: agent
      containers:
      - name: blob-service
        image: docker.io/library/blob-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3003