apiVersion: v1
kind: Pod
metadata:
  name: pod-using-nfs
spec:
  containers:
  - name: app
    image: ubuntu:20.04
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - mountPath: "/mnt/nfs"
      name: nfs-storage
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc