apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: sergiocorne/auth_service:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt/auth
          name: auth-volume
        ports:
        - containerPort: 3001
      volumes:
      - name: auth-volume
        persistentVolumeClaim:
          claimName: pvc-auth