apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  storageClassName: blobstorage
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path:  "/home/ubuntu/blob"
    server: 10.0.2.6
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-auth
spec:
  storageClassName: authstorage
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path:  "/home/ubuntu/auth"
    server: 10.0.2.6
