apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
spec:
  storageClassName: blobstorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-auth
spec:
  storageClassName: authstorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
