apiVersion: v1
kind: Service
metadata:
  name: authsrv-service
  labels:
    app: authsrv
spec:
  type: NodePort
  selector:
    app: authsrv
  ports:
  - protocol: TCP
    port: 3001
    targetPort: port-authsrv
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authsrv-deployment
  labels:
    app: authsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authsrv
  template:
    metadata:
      labels:
        app: authsrv
    spec:
      nodeSelector:
        kubernetes.io/hostname: agent
      containers:
      - name: authsrv-container
        image: nachorozas/authsrv:latest
        imagePullPolicy: Always 
        env:
        - name: token_endpoint
          value: "http://tokensrv-service:3002/api/v1/token"
        - name: STORAGE_FOLDER
          value: "/app/storage"
        command: ["/bin/sh"]
        args: ["-c", "venv/bin/auth_service"]
        ports:
        - name: port-authsrv
          containerPort: 3001
        volumeMounts:
        - name: auth-volume
          mountPath: /app/storage
      volumes:
        - name: auth-volume
          persistentVolumeClaim:
            claimName: pvc-auth
