apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-service
  template:
    metadata:
      labels:
        app: token-service
    spec:
      containers:
      - name: token-service
        image: sergiocorne/token_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002