- name: Ensure NGINX server is installed
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy configuration file
  copy:
    src: "{{ role_path }}/nginx_files/{{ item }}"
    dest: "etc/nginx/nginx.conf"
  with_items:
    - nginx.conf

- name: Restart NGINX server
  shell: |
    service nginx restart
  args:
    executable: /bin/bash
