- name: Install K3S server
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --token {{ k3s_token }} --write-kubeconfig-mode 644
  args:
    executable: /bin/bash

- name: Create manifests directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0664'
    owner: server
    group: server
  with_items:
    - "{{ manifests_path }}"

- name: Ensure NFS client is installed
  apt:
    name: nfs-common
    state: present
    update_cache: yes