k3s_cluster:
  children:
    server:
      hosts:
        192.168.56.111:
          ansible_user: ubuntu
    nfs:
      hosts: 
        192.168.56.113:
          ansible_user: ubuntu
    agent:
      hosts:
        192.168.56.112:
          ansible_user: ubuntu
    nginx:
      hosts:
        192.168.56.110:
          ansible_user: ubuntu
