apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-auth
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /path/to/shared/storage
    server: <NFS_SERVER_IP>
