apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob-test
spec:
  storageClassName: blobstorage-test
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
