apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: local-path  
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  nfs:
    server: 10.42.2.1  
    path: "/nfs/storage_blob"                
